### PR TITLE
Add Chinese

### PR DESCRIPTION
**Pull request by koheiw**
This is for #25 and #26, but `stopwords("zh_cn", "marimo")` does not work because of the ISO code check. I suggest to check language name against `names(data_stopwords_marimo)` instead.

### CODE REVIEW

**Comment by kbenoit** [comment]
We could modify it to use the ISO-639-3 codes as well, which could include ancient languages. Had this problem in `data_stopwords_ancient`, where the three-letter code for ancient Greek was "grc", but I could only use the two-letter code.

For traditional chinese, which would it be from [this list](https://iso639-3.sil.org/code_tables/639/data?title=&field_iso639_cd_st_mmbrshp_639_1_tid=All&name_3=chinese&field_iso639_element_scope_tid=All&field_iso639_language_type_tid=All&items_per_page=200)?

**Comment by koheiw** [comment]
I could not find corresponding code for traditional and simplified Chinese in ISO, maybe because it is a non-linguistic categorization. The difference is more like locale. This is why they are `zh_cn` and `zh_tw`.

https://www.w3.org/International/articles/language-tags/

**Comment by kbenoit** [comment]
OK, we just need to modify the function call to `lookup_iso_639_1()` then. Will do asap.

**Review by kbenoit — APPROVED** [review]
I fixed the names, still works as before but allows any name found in the list. (And still resolves the full name to the code, as before, so "French" works the same as "fr".)

If you are happy with this, go ahead and merge it.

**Pull request merged**
